import logging
import json
import asyncio
from openai import AsyncOpenAI
from typing import Dict
from src.config import OPENROUTER_API_KEY, OPENROUTER_MODEL, SITE_URL, SITE_NAME

logger = logging.getLogger(__name__)

INSTITUTIONAL_SYSTEM_PROMPT = """You are a senior institutional gold futures analyst at a top-tier commodity trading firm. Your reports are read by portfolio managers making million-dollar decisions.

REPORT RULES:
1. Lead with the actionable bias - don't bury the lede
2. Be specific with levels - round numbers matter in Gold
3. Quantify everything - percentages, contracts, sigma levels
4. Flag risks prominently - especially event risk
5. No fluff, no filler - every sentence must add value
6. Use futures terminology: "bid", "offered", "stops", "liquidity pools"
7. Think in terms of positioning: "crowded long", "short squeeze potential"

FORMATTING:
- Use markdown headers and bullets
- Bold key levels and warnings
- Keep it scannable - traders have 30 seconds"""

INSTITUTIONAL_REPORT_TEMPLATE = """Generate a professional institutional Gold Futures (GC) market report using this data:

{market_data}

REQUIRED REPORT STRUCTURE:

# 🏆 GOLD FUTURES INTELLIGENCE BRIEF
**Generated:** [timestamp]
**Bias:** [BULLISH/BEARISH/NEUTRAL] | **Confidence:** [HIGH/MEDIUM/LOW]

---

## ⚡ EXECUTIVE SUMMARY
- One sentence: What's the play today?
- Primary driver
- Key level to watch

---

## 📊 MARKET STRUCTURE
- **VPOC (Volume Point of Control):** [level]
- **Value Area:** [VAH] - [VAL]
- **Regime:** [Trend/Balance/Compressed]
- **Interpretation:** What this means for trade location

---

## 🎯 VOLATILITY LEVELS (Sigma Bands)
| Level | Price | Context |
|-------|-------|---------|
| +2σ | [price] | Extreme resistance |
| +1σ | [price] | Initial resistance |
| **Pivot** | [price] | Current reference |
| -1σ | [price] | Initial support |
| -2σ | [price] | Extreme support |

**Daily Expected Range:** Based on [X]% annualized vol

---

## 🔗 MACRO CORRELATIONS
- **DXY (Dollar):** [correlation] - [interpretation]
- **US10Y (Yields):** [correlation] - [interpretation]
- **Divergence Alert:** [any unusual decoupling]

---

## 📈 COT POSITIONING (Commitment of Traders)
- **Speculators:** [NET LONG/SHORT] [contracts]
- **Positioning Bias:** [crowded/neutral/light]
- **Smart Money (Commercials):** [what are hedgers doing]
- **Implication:** [contrarian signal or trend confirmation]

---

## 📅 EVENT RISK
[List upcoming events with impact assessment]
**Risk Warning:** [if applicable]

---

## 🎲 GAME THEORY SCENARIOS

**SCENARIO A - BULL CASE:**
- Trigger: [condition]
- Target: [level]
- Probability: [%]

**SCENARIO B - BEAR CASE:**
- Trigger: [condition]
- Target: [level]
- Probability: [%]

**INVALIDATION:** [level that negates the primary thesis]

---

## 💡 BOTTOM LINE
[2-3 sentences max. What should the trader DO with this information?]

---
*Report generated by Gold_Sovereign_AI | Data delayed 15min | Not financial advice*
"""


class ReasoningCore:
    def __init__(self):
        self.client = AsyncOpenAI(
            base_url="https://openrouter.ai/api/v1",
            api_key=OPENROUTER_API_KEY,
            default_headers={
                "HTTP-Referer": SITE_URL,
                "X-Title": SITE_NAME
            }
        ) if OPENROUTER_API_KEY else None

    def _format_tradingview_data(self, market_data_dict: Dict) -> str:
        """Format sigma levels and VPOC as CSV for TradingView copy-paste."""
        vol_levels = market_data_dict.get("volatility_levels", {})
        market_structure = market_data_dict.get("market_structure", {})
        
        # Extract values with fallbacks
        sigma_2_up = vol_levels.get("2_sigma_up", 0)
        sigma_1_up = vol_levels.get("1_sigma_up", 0)
        pivot = vol_levels.get("pivot", 0)
        sigma_1_down = vol_levels.get("1_sigma_down", 0)
        sigma_2_down = vol_levels.get("2_sigma_down", 0)
        vpoc = market_structure.get("vpoc", 0)
        
        # Round to 1 decimal place
        csv_data = f"{sigma_2_up:.1f},{sigma_1_up:.1f},{pivot:.1f},{sigma_1_down:.1f},{sigma_2_down:.1f},{vpoc:.1f}"
        
        tradingview_section = f"""

---
## ⚡ TRADINGVIEW DATA ⚡
**Copy-paste for TradingView indicators:**
```
{csv_data}
```
*Format: +2σ, +1σ, pivot, -1σ, -2σ, VPOC*"""
        
        return tradingview_section

    async def generate_report(self, market_data_dict: Dict) -> str:
        """Generate institutional-grade trading intelligence report."""
        if not self.client:
            logger.error("OpenRouter API key not configured")
            return "# ⚠️ Error: API key not configured"

        user_prompt = INSTITUTIONAL_REPORT_TEMPLATE.format(
            market_data=json.dumps(market_data_dict, indent=2, default=str)
        )

        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = await self.client.chat.completions.create(
                    model=OPENROUTER_MODEL,
                    messages=[
                        {"role": "system", "content": INSTITUTIONAL_SYSTEM_PROMPT},
                        {"role": "user", "content": user_prompt}
                    ],
                    temperature=0.7,
                    max_tokens=2500
                )

                report = response.choices[0].message.content
                if not report:
                    return "# ⚠️ Error: Empty response from LLM"
                
                # Append TradingView data section
                tradingview_data = self._format_tradingview_data(market_data_dict)
                report = f"{report}{tradingview_data}"
                
                return report

            except Exception as e:
                if attempt == max_retries - 1:
                    logger.error(f"Error generating report after {max_retries} attempts: {e}")
                    return f"# ⚠️ Error generating report: {str(e)}"
                logger.warning(f"LLM request failed (attempt {attempt + 1}/{max_retries}): {e}. Retrying...")
                await asyncio.sleep(2 * (attempt + 1))
        
        return "# ⚠️ Error: Failed to generate report after retries"
